sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279568.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279568.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279566.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279566.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279561.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279561.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279554.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279554.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279585.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279585.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279553.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279553.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279582.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279582.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279570.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279570.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279577.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279577.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279579.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279579.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279583.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279583.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279555.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279555.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279584.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279584.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279560.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279560.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279567.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279567.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279569.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279569.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279578.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279578.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279576.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279576.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279571.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279571.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279572.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279572.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279575.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279575.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279558.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279558.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/sortedcomb.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/sortedcomb.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279556.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279556.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279580.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279580.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279564.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279564.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279563.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279563.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279574.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279574.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279573.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279573.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279562.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279562.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279565.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279565.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279581.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279581.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279557.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279557.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279586.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279586.bed
sed 's/  */\t/g' /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCbed/SRR3279559.bed > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/SRR3279559.bed
