cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279553.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279553.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279554.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279554.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279555.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279555.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279556.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279556.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279557.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279557.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279558.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279558.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279559.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279559.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279560.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279560.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279561.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279561.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279562.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279562.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279563.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279563.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279564.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279564.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279565.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279565.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279566.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279566.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279567.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279567.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279568.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279568.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279569.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279569.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279570.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279570.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279571.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279571.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279572.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279572.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279573.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279573.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279574.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279574.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279575.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279575.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279576.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279576.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279577.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279577.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279578.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279578.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279579.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279579.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279580.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279580.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279581.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279581.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279582.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279582.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279583.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279583.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279584.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279584.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279585.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279585.txt
cat /cbcb/project-scratch/tinyRNAproj/mapqual/SRR3279586.txt | sort -n | uniq -c > /cbcb/project-scratch/tinyRNAproj/mapqualdist/SRR3279586.txt
