mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279578/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279557/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279556/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279579/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279554/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279555/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279569/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279568/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279553/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279582/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279575/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279562/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279563/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279574/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279583/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279581/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279576/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279559/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279561/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279560/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279558/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279577/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279580/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279564/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279584/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279573/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279572/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279585/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279565/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279567/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279570/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279571/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279586/
mkdir /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/CompositionStats2/SRR3279566/
