import os

for direc in os.listdir("/cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/bylengths/bedfiles/"):
	for file in os.listdir("/cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/bylengths/bedfiles/" + direc + "/"):
		print '/cbcb/project-scratch/tinyRNAproj/software/bedtools-2.17.0/bin/subtractBed -a /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/bylengths/bedfiles/' + direc + '/' + file + ' -b /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/genicregions/3primeutr.bed -A > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/GENICBIAS/3primeremoved/' + direc + '/' + file
		print '/cbcb/project-scratch/tinyRNAproj/software/bedtools-2.17.0/bin/subtractBed -a /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/bylengths/bedfiles/' + direc + '/' + file + ' -b /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/genicregions/5primeutr.bed -A > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/GENICBIAS/5primeremoved/' + direc + '/' + file
		print '/cbcb/project-scratch/tinyRNAproj/software/bedtools-2.17.0/bin/subtractBed -a /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/bylengths/bedfiles/' + direc + '/' + file + ' -b /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/genicregions/codingexons.bed -A > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/GENICBIAS/exonremoved/' + direc + '/' + file
		print '/cbcb/project-scratch/tinyRNAproj/software/bedtools-2.17.0/bin/subtractBed -a /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/bylengths/bedfiles/' + direc + '/' + file + ' -b /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/genicregions/introns.bed -A > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/GENICBIAS/intronremoved/' + direc + '/' + file
		print '/cbcb/project-scratch/tinyRNAproj/software/bedtools-2.17.0/bin/subtractBed -a /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/bylengths/bedfiles/' + direc + '/' + file + ' -b /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/genicregions/upstream.bed -A > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/GENICBIAS/upstream/' + direc + '/' + file
		print '/cbcb/project-scratch/tinyRNAproj/software/bedtools-2.17.0/bin/subtractBed -a /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/bylengths/bedfiles/' + direc + '/' + file + ' -b /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/genicregions/downstream.bed -A > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/GENICBIAS/downstream/' + direc + '/' + file
