import os

for file in os.listdir("/cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/"):
	print '/cbcb/project-scratch/tinyRNAproj/software/bedtools-2.17.0/bin/subtractBed -a /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/' + file + ' -b /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/genicregions/3primeutr.bed -A > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/genicregionremovedbed/3prime/' + file
	print '/cbcb/project-scratch/tinyRNAproj/software/bedtools-2.17.0/bin/subtractBed -a /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/' + file + ' -b /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/genicregions/5primeutr.bed -A > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/genicregionremovedbed/5prime/' + file
	print '/cbcb/project-scratch/tinyRNAproj/software/bedtools-2.17.0/bin/subtractBed -a /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/' + file + ' -b /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/genicregions/codingexons.bed -A > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/genicregionremovedbed/exon/' + file
	print '/cbcb/project-scratch/tinyRNAproj/software/bedtools-2.17.0/bin/subtractBed -a /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/' + file + ' -b /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/genicregions/introns.bed -A > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/genicregionremovedbed/intron/' + file
	print '/cbcb/project-scratch/tinyRNAproj/software/bedtools-2.17.0/bin/subtractBed -a /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/' + file + ' -b /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/genicregions/upstream.bed -A > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/genicregionremovedbed/upstream/' + file
	print '/cbcb/project-scratch/tinyRNAproj/software/bedtools-2.17.0/bin/subtractBed -a /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/uniqueEndCBed/' + file + ' -b /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/genicregions/downstream.bed -A > /cbcb/project-scratch/tinyRNAproj/samples/FINALSAMPLES/genicregionremovedbed/downstream/' + file
